#+TITLE: Portfolio
#+AUTHOR: Samriddha Chattopadhyay (Samy)

* ABOUT THE PROJECT

This is my personal portfolio website. You can fork this repo to modify and make changes of your own. Please give me proper credit by linking back to [[https://github.com/Samyc2002][Samy.exe]]. Thanks!

* BUILT WITH

My personal portfolio [[https://github.com/Samyc2002][Samy.exe]].tech which features some of my github projects as well as my resume and technical skills.

This project has been built using these technologies:
+ Next.js
+ React.js
+ Node.js
+ Express.js
+ CSS3
+ VS Code
+ Emacs
+ Linux
+ Figma
+ Material UI
+ Netlify

* Features

+ 📖 Multi-Page Layout
+ 🎨 Styled with React-Bootstrap and Css with easy to customize colors
+ 📱 Fully Responsive

* GETTING STARTED
Clone down this repository. You will need ~node.js~ and ~git~ installed globally on your machine.

* 🛠 Installation and Setup Instructions
 1. Installation: ~npm install~
 2. Run the following commands in the project folder:
    #+begin_src bash
        cd Project
        npm run dev
    #+end_src

This runs the project in development mode.
Open http://localhost:3000 to view it in the browser. Consecutively, you can also see it running in your terminal.

* Usage Instructions

Open the project folder and Navigate to ~/Project/src/components/~.
You will find all the components used and you can edit your information accordingly.

~/Project/src/pages~ has all the components arranged and organised in pages.

* Show your support
Give a ⭐ if you like this website!
