import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"
import NavBar from '@/components/custom/navbar';
import { Toaster } from '@/components/ui/sonner';
import Footer from '@/components/custom/footer';
import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Samy.exe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          <main className="px-10 md:px-40 xl:px-64 pb-10">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
