import Head from 'next/head';
import type { AppProps } from 'next/app';

import { Navbar, Contact } from '../components';
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Samy.exe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo_Dark.png" />
      </Head>
      <Navbar/>
      <Component {...pageProps} />
      <Contact/>
    </>
  );
}

export default MyApp;
