import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import Header from '../components/Header';
import Footer from '../components/Footer';
import styles from '../styles/Root.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Samy.exe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo-Dark.png" />
      </Head>

      <Header/>
      <main className={styles.main}>
        Content
      </main>
      <Footer/>
    </div>
  )
}

export default Home
