import Head from 'next/head';
import Image from 'next/image';
import type { NextPage } from 'next';
import { Grid } from '@material-ui/core';
import { useMediaQuery } from 'react-responsive';

import { useStyles } from '../styles/Projects.styles';
import styles from '../styles/Projects.module.css';
import { Navbar, GithubCard } from '../components';
import { Card, GithubCard as GCard } from '../globals';

const Projects: NextPage = () => {

  const classes = useStyles();

  const isTabletorMobile = useMediaQuery({ query: '(max-width: 900px)' });
  const isTabletorMobileSmall = useMediaQuery({ query: '(max-width: 780px)' });

  return (
    <>
      <Head>
        <title>Samy.exe - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo_Dark.png" />
      </Head>
      <Navbar />
      <div className={classes.toolbar} />
      <br/>
      {isTabletorMobileSmall && (
        <>
          <br/><br/><br/>
        </>
      )}
      <div className={styles.padding}>
        <h2 className={styles.h2}>
          Some <span className={styles.projects}><u>Projects</u></span> I Have Recently Worked Upon
        </h2>
        <br/><br/>
        <Grid container spacing={3} justifyContent="center" alignItems="center">
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <GithubCard repo="Coders-Garage" image="/Background.png"/>
          </Grid>
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <GithubCard repo="React-IDE" image="/Background.png"/>
          </Grid>
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <GithubCard repo="Video-Calls" image="/Background.png"/>
          </Grid>
        </Grid>
        <br/><br/><br/><br/>
        <h2 className={styles.h2}>
          My Work <span className={styles.experience}><u>Experience</u></span>
        </h2>
        <br/><br/>
        <Grid container spacing={3} justifyContent="center" alignItems="center">
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <Card caption="Full Stack Developer at Youniv">
              <Image
                  src="/Youniv.png"
                  alt="Image"
                  width={768}
                  height={300}
              />
            </Card>
          </Grid>
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <GCard user="ashishakash" repo="Gymkhana" image="/Background.png"/>
          </Grid>
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <GCard user="oss2019" repo="Codeforces-Leaderboard" image="/Background.png"/>
          </Grid>
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <GCard user="oss2019" repo="Certy" image="/Background.png"/>
          </Grid>
        </Grid>
        <br/><br/><br/><br/>
        <h2 className={styles.h2}>
          My <span className={styles.management}><u>Management</u></span> Related Work
        </h2>
        <br/><br/>
        <Grid container spacing={3} justifyContent="center" alignItems="center">
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <Card caption="PARSEC 2022 - Design team Lead">
              <Image
                  src="/PARSEC.png"
                  alt="Image"
                  width={768}
                  height={300}
              />
            </Card>
          </Grid>
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <Card caption="Logorithmic - Organiser">
              <Image
                  src="/IITC.jpeg"
                  alt="Image"
                  width={768}
                  height={300}
              />
            </Card>
          </Grid>
          <Grid item xs={12} sm={12} md={6} lg={4} xl={3}>
            <Card caption="Summer of Innovation - Organiser">
              <Image
                  src="/SOI.jpg"
                  alt="Image"
                  width={768}
                  height={300}
              />
            </Card>
          </Grid>
        </Grid>
      </div>
    </>
  )
}

export default Projects;
