import Head from 'next/head';
import type { NextPage } from 'next';

import { useStyles } from '../styles/Projects.styles';
import styles from '../styles/Projects.module.css';
import { Navbar } from '../components';

const Projects: NextPage = () => {

  const classes = useStyles();

  return (
    <>
      <Head>
        <title>Samy.exe - Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo_Dark.png" />
      </Head>
      <Navbar />
      <div className={classes.toolbar} />
    </>
  )
}

export default Projects;
